###
POST localhost:5201/api/account
Content-Type: application/json
Accept: application/json

{
  "AccountType": "Personal",
  "CompanyName": "My Company Name",
  "FirstName": "My_First_Name",
  "LastName": "My_Last_Name",
  "PhoneNumber": "000-000-0000",
  "Email": "first.last@email.com",
  "Active": "true"
}

###
PUT localhost:5201/api/Account/465537d1-d5a2-4e4a-861d-7df332547fe1
Content-Type: application/json
Accept: application/json

{
  "Id": "465537d1-d5a2-4e4a-861d-7df332547fe1",
  "AccountType": "Personal",
  "CompanyName": "My Company Name",
  "FirstName": "First",
  "LastName": "Last",
  "PhoneNumber": "000-000-0000",
  "Email": "first.last@email.com",
  "Active": "true"
}

###
GET localhost:5201/api/Account/465537d1-d5a2-4e4a-861d-7df332547fe1
Accept: application/json

###
DELETE localhost:5201/api/Account/465537d1-d5a2-4e4a-861d-7df332547fe1
Accept: application/json

###
