###
POST localhost:5201/api/account
Content-Type: application/json
Accept: application/json

{
  "Id": null,
  "Timestamp": null,
  "FirstName": "My_First_Name",
  "LastName": "My_Last_Name",
  "PhoneNumber": "000-000-0000",
  "Email": "first2.last2@email.com",
  "Type": "Personal",
  "Active": true
}
> {%
    client.global.set("account_id", response.body.id)
%}

###
PUT localhost:5201/api/Account/{{account_id}}
Content-Type: application/json
Accept: application/json

{
  "Id": "{{account_id}}",
  "Timestamp": null,
  "CompanyName": "My Company Name",
  "FirstName": "First",
  "LastName": "Last",
  "PhoneNumber": "000-000-0000",
  "Email": "first.last@email.com",
  "Type": "Personal",
  "Active": true
}

###
GET localhost:5201/api/Account/{{account_id}}
Accept: application/json

###
DELETE localhost:5201/api/Account/{{account_id}}
Accept: application/json

###
POST localhost:5201/api/cart
Content-Type: application/json
Accept: application/json

{
  "Id": null,
  "Timestamp": null,
  "AccountId": "{{account_id}}",
  "Items": null,
  "Active": true
}
> {% client.global.set("cart_id", response.body.id) %}

###
GET localhost:5201/api/cart/{{cart_id}}
Accept: application/json

###
DELETE localhost:5201/api/cart/{{cart_id}}
Accept: application/json

###
POST localhost:5201/api/Order
Accept: application/json
Content-Type: application/json

{
  "AccountId": "{{account_id}}",
  "CartId": "{{cart_id}}",
  "Status": "New",
  "Active": true
}
> {% client.global.set("order_id", response.body.id) %}

###
GET localhost:5201/api/Order/{{order_id}}
Accept: application/json

###
DELETE localhost:5201/api/Account/e2a7468f-7e5b-4522-a954-22a86c822f00
Accept: application/json

###
GET localhost:5201/api/Account
Accept: application/json

###
